# Put action within a raw block so that the curly bracket expressions aren't picked up by the cookiecutter
#
name: Checks

env:
  DOCKER_BUILDKIT: 1

on:
  push:
    paths:
      - mcp_server/**
      - parliament_mcp/**
      - pyproject.toml
      - uv.lock
    branches:
      - 'main'
      - 'feature/**'
      - 'chore/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'develop'
      - 'dependabot/**'
      - 'security/**'
  workflow_dispatch:

jobs:
  static_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install uv
        run: |
          pip install uv

      - name: Install dependencies
        run: |
          uv sync --dev

      - name: Format code
        run: |
          uv run ruff format . --check
          uv run ruff check .

  # run_tests:
  #   name: Run tests

  #   runs-on: ubuntu-latest
  #   environment: release

  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: Copy env file
  #     run: |
  #       cp .env.example .env

  #   - name: Set up Python 3.12
  #     uses: actions/setup-python@v3
  #     with:
  #         python-version: "3.12"

  #   - name: Install uv
  #     run: |
  #       pip install uv

  #   - name: Install dependencies
  #     run: |
  #       uv sync --group dev

  #   - name: Run tests
  #     run: |
  #       make test
#
